language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    #- android-19

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    #- sys-img-x86-android-17
env:
  global:
  - ANDROID_API_LEVEL=21
  - ANDROID_BUILD_TOOLS_VERSION=21.1.2
  - ANDROID_ABI=armeabi-v7a
   # install timeout in minutes (2 minutes by default)
  - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 & #Unluck the device

#script:
#  By default it will run build and connectedCheck (The check anchor tasks have connectedAndroidTest and connectedUiAutomatorTest as dependencies)
#  - ./gradlew build connetedCheck # == build connectedAndroidTest connectedUiAutomatorTest

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
